### ISSUE TITLE
django template not found problem

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#173]
Description: https://keeper.mpdl.mpg.de/home/wiki/ throws 
```
Page unavailable
Sorry, but the requested page is unavailable due to a server hiccup.
Our engineers have been notified, so check back later.
```
seahub_django_request.log:
```
2017-03-31 17:00:36,557 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /home/wiki/
Traceback (most recent call last):
  File "/opt/seafile/seafile-pro-server-6.0.7/seahub/thirdpart/Django-1.8.17-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/seafile/seafile-pro-server-6.0.7/seahub/seahub/auth/decorators.py", line 27, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/seafile/seafile-pro-server-6.0.7/seahub/seahub/base/decorators.py", line 40, in _decorated
    return func(request, *args, **kwargs)
  File "/opt/seafile/seafile-pro-server-6.0.7/seahub/seahub/views/wiki.py", line 71, in personal_wiki
    }, context_instance=RequestContext(request))
  File "/opt/seafile/seafile-pro-server-6.0.7/seahub/thirdpart/Django-1.8.17-py2.7.egg/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/opt/seafile/seafile-pro-server-6.0.7/seahub/thirdpart/Django-1.8.17-py2.7.egg/django/template/loader.py", line 137, in render_to_string
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: wiki/personal_wiki.html
```
Location: only keeper PROD, not reproducible on QA and DEV

**Comment by vmakarenko** [comment]
Resolved: 
- problem's source is not wiped out template seahub-data/custom/templates/home_base.html. This caused a TemplateDoesNotExist exception by loading of extended template myhome_base.html
- inconsistent error logging by Django: exception message showed template which exists, but not the template which caused the problem (location: https://github.com/django/django/blob/1.8.17/django/template/loader.py#L131)
